### ISSUE TITLE
Pre Work Lesson: JavaScript Data Types

### ISSUE THREAD

**Issue by VeraKulemina** [learn-co-curriculum/phase-0-pac-1-js-data-types#5]
### Canvas Link

https://learning.flatironschool.com/courses/6042/pages/javascript-data-types?module_item_id=449755

### Concern

In this lesson, you name 7 data types. Then you name Arrays as the Data type. This is will be 8 data types. But you are not including arrays at the end of the lesson as data type. Is that an error of the lesson or you did do that on purpose? If it's on purpose then why you are not including arrays?

### Suggested Changes

I suggest or to include or exclude arrays and explain why. Thank you

**Comment by lizbur10** [comment]
Hi @VeraKulemina ! Thanks for posting this issue - the description of arrays has now been clarified 💙

**Comment by VeraKulemina** [comment]
Hi Liz! Thank you!
