### ISSUE TITLE
Seems Like an Error in the README file

### ISSUE THREAD

**Issue by Anton-Kalyutich** [learn-co-curriculum/phase-0-pac-1-js-data-types#9]
### Canvas Link

https://learning.flatironschool.com/courses/6670/pages/javascript-data-types?module_item_id=535640

### Concern

This code sample under Objects paragraph seems to have a mistake (last expression referring to an empty object rather than the declared one):

const js = {
  name: "JavaScript",
  createdBy: {
    firstName: "Brendan",
    lastName: "Eich",
  },
  firstReleased: 1995,
  isAwesome: true,
};

typeof {};
//=> "object"

### Suggested Changes

const js = {
  name: "JavaScript",
  createdBy: {
    firstName: "Brendan",
    lastName: "Eich",
  },
  firstReleased: 1995,
  isAwesome: true,
};

**typeof js**;
//=> "object"

**Comment by DavidWolff218** [comment]
Hello, and thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved.
Note, however, that if you are working in Canvas the changes may not show up
there, but they will for future students.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not!
We appreciate your support!

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
